project:
  type: book
  output-dir: _book

book:
  title: "Computational Astronomy"
  reader-mode: true

  page-footer:
    left: |
      Computational Astronomy was written by Scott Briggs.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    #- preface.qmd
    #- intro.qmd
    - math-necessities.qmd
    - unit-conversions.qmd
    - time-conversions.qmd
    - coordinate-systems.qmd
    - de441.qmd
    - references.qmd

bibliography: references.bib
csl: turabian-author-date.csl

format:
  html:
    theme:
      light: [flatly, computational-astronomy.scss]
      dark: [darkly, computational-astronomy.scss]
    respect-user-color-scheme: true
    code-link: true

    author-meta: "Scott Briggs"
    callout-appearance: simple

editor: visual